version: '3'

services:

  web_service:
    labels:
      shipyard.route: '/'
    build: '.'
    env_file: 'environments/dev.env'
    depends_on:
      - postgres
      - redis
    ports:
      - '8080:8080'

  worker_service:
    build: '.'
    env_file:
      - 'environments/dev.env'
    depends_on:
      - web_service

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'flask_app'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:4-alpine'

volumes:
  postgres:
